imports:
    - { resource: 'services/temporal.yaml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Finconsult\Documentor\Shared\:
        resource: '../'
        exclude:
            - '../src/Shared/**/DependencyInjection/'
            - '../src/Shared/Contexts/'
            - '../src/Shared/Layers/Infrastructure/Controller/GraphQL/DependencyInjection/'
            - '../src/Shared/Layers/Model/'
            - '../src/Shared/Kernel.php'

    # Exception listener
    Finconsult\Documentor\Shared\Layers\Infrastructure\EventListener\RedirectingExceptionListener:
        public: true
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    # GraphQL
    Finconsult\Documentor\Shared\Layers\Infrastructure\Controller\GraphQL\Schema\:
        resource: '../Layers/Infrastructure/Controller/GraphQL/Schema'
        public: true

    Finconsult\Documentor\Shared\Layers\Infrastructure\Controller\GraphQL\Exception\ExceptionConverter: ~

    Overblog\GraphQLBundle\Error\ExceptionConverterInterface:
        class: 'Finconsult\Documentor\Shared\Layers\Infrastructure\Controller\GraphQL\Exception\ExceptionConverter'


    # Security
    Finconsult\Documentor\Shared\Contexts\Security\:
        resource: '../Contexts/Security'
        exclude:
            - '../Contexts/Security/Model/Entity/'
