services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Finconsult\Documentor\:
        resource: '../src/'
        exclude:
            - '../src/Account/'
            - '../src/Blanks/'
            - '../src/Clients/'
            - '../src/EACs/'
            - '../src/Positions/'
            - '../src/Shared/Contexts/'
            - '../src/Shared/Model/'
            - '../src/Shared/Security/'
            - '../src/Shared/Temporal/Initialization/'
            - '../src/Shared/Kernel.php'

    Finconsult\Documentor\Shared\Controller\:
        resource: '../src/Shared/Controller'
        tags: ['controller.service_arguments']

    # Temporal
    Finconsult\Documentor\Shared\Temporal\Initialization\TemporalContainer: ~
    Temporal\Client\WorkflowClient:
        factory: ['Finconsult\Documentor\Shared\Temporal\WorkflowClientProvider', 'instance']
