services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Temporal/Initialization/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Temporal
    App\Temporal\Initialization\TemporalContainer: ~
    App\Temporal\ActivityInterface: ~
    App\Temporal\WorkflowInterface: ~
