services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Finconsult\Documentor\:
        resource: '../src/'
        exclude:
            - '../src/Temporal/Initialization/'
            - '../src/Kernel.php'

    Finconsult\Documentor\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Temporal
    Finconsult\Documentor\Temporal\Initialization\TemporalContainer: ~
    Finconsult\Documentor\Temporal\ActivityInterface: ~
    Finconsult\Documentor\Temporal\WorkflowInterface: ~
