services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Finconsult\Documentor\:
        resource: '../src/'
        exclude:
            - '../src/Blanks/'
            - '../src/Clients/'
            - '../src/EACs/'
            - '../src/Positions/'
            - '../src/Shared/'
