services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Finconsult\Documentor\:
        resource: '../src/'
        exclude:
            - '../src/Shared/Temporal/Initialization/'
            - '../src/Shared/Kernel.php'

    Finconsult\Documentor\Shared\Controller\:
        resource: '../src/Shared/Controller'
        tags: ['controller.service_arguments']

    # Temporal
    Finconsult\Documentor\Shared\Temporal\Initialization\TemporalContainer: ~
    Finconsult\Documentor\Shared\Temporal\ActivityInterface: ~
    Finconsult\Documentor\Shared\Temporal\WorkflowInterface: ~
