version: "3.5"

services:

    postgresql:
        container_name: finconsult2-postgresql
        image: postgres:13
        environment:
            POSTGRES_PASSWORD: temporal
            POSTGRES_USER: temporal
        ports:
            - 5432:5432

    temporal:
        container_name: finconsult2-temporal
        image: temporalio/auto-setup:1.16.2
        depends_on:
            - postgresql
        environment:
            - DB=postgresql
            - DB_PORT=5432
            - POSTGRES_USER=temporal
            - POSTGRES_PWD=temporal
            - POSTGRES_SEEDS=postgresql
            - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
        ports:
            - 7233:7233

    temporal-admin-tools:
        container_name: finconsult2-temporal-admin-tools
        image: temporalio/admin-tools:1.16.2
        depends_on:
            - temporal
        environment:
            - TEMPORAL_CLI_ADDRESS=temporal:7233
        stdin_open: true
        tty: true

    temporal-web:
        container_name: finconsult2-temporal-web
        image: temporalio/web:1.13.0
        depends_on:
            - temporal
        environment:
            - TEMPORAL_GRPC_ENDPOINT=temporal:7233
            - TEMPORAL_PERMIT_WRITE_API=true
        ports:
            - 8088:8088

    app:
        container_name: finconsult2-app
        build:
            context: ../app
        depends_on:
            - temporal
            - postgresql
        ports:
            - "8080:8080"
        volumes:
            - ./../app:/var/app
        environment:
            - APP_ENV=dev
            - APP_DEBUG=true
            - TEMPORAL_CLI_ADDRESS=temporal:7233
            - TEMPORAL_NAMESPACE=default
        command: [ "/usr/local/bin/wait-for-temporal.sh", "temporal", "/usr/local/bin/rr", "serve", "-c", "/var/app/.rr.yaml" ]
        restart: unless-stopped
        healthcheck:
            test: curl -f http://localhost:1112/health?plugin=http || exit 1
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 15s
