version: "2.7"

server:
    command: "php worker.php"
    env:
        - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

http:
    address: 0.0.0.0:8079
    ssl:
        address: :8080
        redirect: true
        cert: config/certs/public.crt
        key: config/certs/secret.key
    internal_error_code: 505
    middleware: ["static", "gzip"]
    uploads:
        forbid: [".php", ".exe", ".bat", ".sh", ".bash"]
    static:
        dir: "public"
        forbid: [".php"]
    pool:
        num_workers: 2

temporal:
    address: temporal:7233
    activities:
        num_workers: 4

rpc:
    listen: tcp://127.0.0.1:6001

status:
    address: localhost:1112

logs:
    mode: development
    encoding: console
    line_ending: "\n"
    channels:
        server:
            level: debug
            mode: raw
        http:
            level: debug
        temporal:
            level: debug
