doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        charset: utf8mb4
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Shared\Model:
                dir: '%kernel.project_dir%/src/Shared/Layers/Model'
                prefix: 'Finconsult\Documentor\Shared\Layers\Model'
                alias: Shared\Model
            Shared\Security:
                dir: '%kernel.project_dir%/src/Shared/Contexts/Security'
                prefix: 'Finconsult\Documentor\Shared\Contexts\Security'
                alias: Shared\Security

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
