overblog_graphql:
    definitions:
        schema:
            root:
                query: RootQuery
                mutation: RootMutation
            public:
                query: PublicQuery
                mutation: PublicMutation
        mappings:
            types:
                # Shared\GraphQL
                -   type: attribute
                    dir: "%kernel.project_dir%/src/Shared/Layers/Infrastructure/Controller/GraphQL"
                    suffix: ~
                # Shared\Model
                -   type: attribute
                    dir: "%kernel.project_dir%/src/Shared/Layers/Model"
                    suffix: ~
                # Shared\Security
                -   type: attribute
                    dir: "%kernel.project_dir%/src/Shared/Contexts/Security"
                    suffix: ~
